name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'sbt'
      - name: Install SBT
        uses: sbt/setup-sbt@v1
      - name: Test
        run: sbt -v test